baseURL = "https://defn.io/"
title = "defn.io"
theme = "terminal"
languageCode = "en-us"
copyright = "(c) 2015-2019 Bogdan Popa"
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"

[Author]
  name = "Bogdan Popa"

[Taxonomies]
  tag = "tags"

[Params]
  subtitle = "Bogdan Popa"
  contentTypeName = "post"
  themeColor = "red"
  fullWidthTheme = false
  centerTheme = true

[Params.logo]
  logoText = "defn.io"

[Permalinks]
  post = "/:year/:month/:day/:filename/"

[[menu.main]]
  name = "Posts"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/page/projects/"
  weight = 2

[[menu.main]]
  name = "Talks I Like"
  url = "/page/talks-i-like/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 4
