theme = "even"
title = "defn.io"
baseURL = "https://defn.io/"
languageCode = "en-us"
defaultContentLanguage = "en"

pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[author]
  name = "Bogdan Popa"

[Taxonomies]
  tag = "tags"

[params]
  version = "4.x"

  since = "2014"
  gitRepo = "https://github.com/Bogdanp/personal-website"

  logoTitle = "defn.io"

  archivePaginate = 25

  [params.social]
    a-twitter = "https://mas.to/@bogdanp"
    b-github = "https://github.com/Bogdanp"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[[menu.main]]
  name = "Posts"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/page/projects/"
  weight = 2

[[menu.main]]
  name = "Talks"
  url = "/page/talks/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true