baseURL = "https://defn.io/"
title = "defn.io"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Bogdan Popa"

[Author]
    name = "Bogdan Popa"

[Taxonomies]
    tag = "tags"

[Params]
    intro = false
    headline = "My headline"
    description = "My description"
    github = "https://github.com/Bogdanp"
    linkedin = "https://linkedin.com/in/popabogdanp/"
    twitter = "https://twitter.com/Bogdanp"
    email = "bogdan@defn.io"
    opengraph = true
    shareGooglePlus = false
    shareFacebook = false
    shareTwitter = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/page/projects/"
    weight = 2

[[menu.main]]
    name = "Talks I Like"
    url = "/page/talks-i-like/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
